var quotations = [
	["The truth is rarely pure and never simple."],
	["Oscar Wilde"],
	["Live as if you were to die tomorrow. Learn as if you were to live forever."],
	["Mahatma Gandhi"],
	["The future depends on what you do today."],
	["Mahatma Gandhi"],
	["A man is but the product of his thoughts. What he thinks, he becomes."],
	["Mahatma Gandhi"],
	["Man often becomes what he believes himself to be. If I keep on saying to myself that I cannot do a certain thing, it is possible that I may end by really becoming incapable of doing it. On the contrary, if I have the belief that I can do it, I shall surely acquire the capacity to do it even if I may not have it at the beginning."],
	["Mahatma Gandhi"],
	["To believe in something, and not to live it, is dishonest."],
	["Mahatma Gandhi"],
	["Whatever you do will be insignificant, but it is very important that you do it."],
	["Mahatma Gandhi"],
	["Strength does not come from physical capacity. It comes from an indomitable will."],
	["Mahatma Gandhi"],
	["Action expresses priorities."],
	["Mahatma Gandhi"],
	["You may never know what results come of your actions, but if you do nothing, there will be no results."],
	["Mahatma Gandhi"],
	["Love is the strongest force the world possesses and yet it is the humblest imaginable."],
	["Mahatma Gandhi"],
	["They cannot take away our self respect if we do not give it to them."],
	["Mahatma Gandhi"],
	["Always aim at complete harmony of thought and word and deed. Always aim at purifying your thoughts and everything will be well."],
	["Mahatma Gandhi"],
	["Each one has to find his peace from within. And peace to be real must be unaffected by outside circumstances."],
	["Mahatma Gandhi"],
	["There is no such thing as 'too insane' unless others turn up dead due to your actions."],
	["Mahatma Gandhi"],
	["Be the change that you wish to see in the world."],
	["Mahatma Gandhi"],
	["Everything is energy. Your thought begins it, your emotion amplifies it and your action increases the momentum."],
	["Unknown"],
	["When you are willing to feel it, you can heal it."],
	["Unknown"],
	["Don't cry because it's over, smile because it happened."],
	["Unknown"],
	["Twenty years from now you will be more disappointed by the things you didn’t do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover."],
	["Unknown"],
	["This is your life, and it's ending one minute at a time."],
	["Unknown"],
	["Do not look for approval except for the consciousness of doing your best."],
	["Andrew Carnegie"],
	["So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about."],
	["Marilyn Monroe"],
	["Don't Worry, Be Happy"],
	["Unknown"],
	["A disciplined mind leads to happiness, and an undisciplined mind leads to suffering."],
	["Dalai Lama XIV"],
	["Never argue with stupid people, they will drag you down to their level and then beat you with experience."],
	["Mark Twain"],
	["Whenever you find yourself on the side of the majority, it is time to reform (or pause and reflect)."],
	["Mark Twain"],
	["The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time."],
	["Mark Twain"],
	["Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great."],
	["Mark Twain"],
	["Never allow someone to be your priority while allowing yourself to be their option."],
	["Mark Twain"],
	["Truth is stranger than fiction, but it is because Fiction is obliged to stick to possibilities; Truth isn't."],
	["Mark Twain"],
	["You can't depend on your eyes when your imagination is out of focus."],
	["Mark Twain"],
	["If you don't read the newspaper, you're uninformed. If you read the newspaper, you're mis-informed."],
	["Mark Twain"],
	["Courage is resistance to fear, mastery of fear - not absence of fear."],
	["Mark Twain"],
	["It's not the size of the dog in the fight, it's the size of the fight in the dog."],
	["Mark Twain"],
	["Education: the path from cocky ignorance to miserable uncertainty."],
	["Mark Twain"],
	["The easy confidence with which I know another man's religion is folly teaches me to suspect that my own is also."],
	["Mark Twain"],
	["The worst loneliness is to not be comfortable with yourself."],
	["Mark Twain"],
	["A clear conscience is the sure sign of a bad memory."],
	["Mark Twain"],
	["April 1. This is the day upon which we are reminded of what we are on the other three hundred and sixty-four."],
	["Mark Twain"],
	["Out of all the things I have lost, I miss my mind the most."],
	["Mark Twain"],
	["Any emotion, if it is sincere, is involuntary."],
	["Mark Twain"],
	["The most interesting information come from children, for they tell all they know and then stop."],
	["Mark Twain"],

	//[""],
	//[""],

	["A truly strong person does not need the approval of others any more than a lion needs the approval of sheep."],
	["Vernon Howard"],
	["Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world, stimulating progress, giving birth to evolution."],
	["Albert Einstein"]
]
